[package]
name = "csv-converter"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.1"

[dev-dependencies]
assert_cmd = "2.0.17"
tempfile = "3.20.0"

[[bin]]
name = "csvc"
path = "src/main.rs"
